PixelVrtic/PixelVrtic/Models/Aktivnost.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace PixelVrtic.Models
{
    public class Aktivnost
    {
        public Aktivnost() { }

        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "Naziv aktivnosti je obavezan.")]
        [StringLength(100, ErrorMessage = "Naziv aktivnosti može sadržavati najviše 100 karaktera.")]
        [RegularExpression(@"^[A-ZĆČŽŠĐa-zćčžšđ0-9 \-]+$", ErrorMessage = "Naziv aktivnosti može sadržavati samo slova, brojeve, razmake i crtice.")]
        public string nazivAktivnosti { get; set; }

        [Required(ErrorMessage = "Tip aktivnosti je obavezan.")]
        public TipAktivnosti tipAktivnosti { get; set; }

        [Required(ErrorMessage = "Datum početka je obavezan.")]
        [DataType(DataType.DateTime)]
        public DateTime datumPocetka { get; set; }

        [Required(ErrorMessage = "Datum završetka je obavezan.")]
        [DataType(DataType.DateTime)]
        [CustomValidation(typeof(Aktivnost), nameof(ValidirajDatume))]
        public DateTime datumZavrsetka { get; set; }


        [StringLength(1000, ErrorMessage = "Opis može sadržavati najviše 1000 karaktera.")]
        [RegularExpression(@"^[A-ZĆČŽŠĐa-zćčžšđ0-9\s.,!?\-–()]*$", ErrorMessage = "Opis sadrži nedozvoljene karaktere.")]
        public string opis { get; set; }

        [ForeignKey("Grupa")]
        [Required(ErrorMessage = "Grupa aktivnosti je obavezna.")]
        public int idGrupe { get; set; }

        [ValidateNever]
        public Grupa Grupa { get; set; }

        [ForeignKey("Korisnik")]
        [Required(ErrorMessage = "Organizator aktivnosti je obavezan.")]
        public string idKorisnika { get; set; }

        [ValidateNever]
        public Korisnik Korisnik { get; set; }

        [StringLength(255, ErrorMessage = "Putanja fotografije može sadržavati najviše 255 karaktera.")]
        public string? fotografija { get; set; }

        public static ValidationResult ValidirajDatumPocetka(DateTime datumPocetka, ValidationContext context)
        {
            if (datumPocetka < DateTime.Today.AddYears(-1))
                return new ValidationResult("Datum početka ne može biti više od godinu dana u prošlosti.");

            return ValidationResult.Success;
        }


        public static ValidationResult ValidirajDatume(DateTime datumZavrsetka, ValidationContext context)
        {
            var instance = context.ObjectInstance as Aktivnost;
            if (instance == null)
                return ValidationResult.Success;

            if (datumZavrsetka < instance.datumPocetka)
                return new ValidationResult("Datum završetka ne može biti prije datuma početka.");

            if ((datumZavrsetka - instance.datumPocetka).TotalDays > 30)
                return new ValidationResult("Trajanje aktivnosti ne može biti duže od 30 dana.");

            return ValidationResult.Success;
        }
    }
}

PixelVrtic/PixelVrtic/Controllers/AktivnostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PixelVrtic.Data;
using PixelVrtic.Models;

namespace PixelVrtic.Controllers
{
    [Authorize]
    public class AktivnostController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<Korisnik> _userManager;


        public AktivnostController(ApplicationDbContext context, UserManager<Korisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private void PostaviVaspitaceViewData(object selectedId = null)
        {
            // Dohvati korisnike koji imaju ulogu s id=2
            var roditelji = _context.Korisnik
                .Where(k => k.uloga != null && (int)k.uloga == 1)
                .ToList();


            ViewData["idKorisnika"] = new SelectList(roditelji, "Id", "ime", selectedId);
        }
        // GET: Aktivnost

        public IActionResult Index(int? year, int? month)
        {
            var selectedYear = year ?? DateTime.Now.Year;
            var selectedMonth = month ?? DateTime.Now.Month;

            var aktivnosti = _context.Aktivnost
            .Include(a => a.Grupa)
            .Include(a => a.Korisnik)
            .Where(a => a.datumPocetka.Year == selectedYear && a.datumPocetka.Month == selectedMonth)
            .ToList();

            var user = HttpContext.User;
            ViewBag.IsAuthorizedUser = user.IsInRole("Administrator") || user.IsInRole("Vaspitac") || user.IsInRole("Roditelj");
            ViewBag.Year = selectedYear;
            ViewBag.Month = selectedMonth;

            return View(aktivnosti);
        }


        // GET: Aktivnost/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aktivnost = await _context.Aktivnost
                .Include(a => a.Grupa)
                .Include(a => a.Korisnik)
                .FirstOrDefaultAsync(m => m.id == id);
            if (aktivnost == null)
            {
                return NotFound();
            }

            return View(aktivnost);
        }

        // GET: Aktivnost/Create
        [Authorize(Roles = "Administrator, Vaspitac")]

        public IActionResult Create(string datumPocetka)
        {
            var users = _userManager.Users.ToList(); // Materialize to prevent issues
            ViewData["idGrupe"] = new SelectList(_context.Grupa.ToList(), "id", "naziv");
            PostaviVaspitaceViewData();
            ViewBag.TipAktivnosti = new SelectList(Enum.GetValues(typeof(TipAktivnosti)));

            var model = new Aktivnost();

            if (!string.IsNullOrEmpty(datumPocetka))
            {
                if (DateTime.TryParse(datumPocetka, out var parsedDate))
                {
                    model.datumPocetka = parsedDate;
                    model.datumZavrsetka = parsedDate;
                }
                else
                {
                    model.datumPocetka = DateTime.Today;
                    model.datumZavrsetka = DateTime.Today;
                }
            }

            return View(model);
        }





        // POST: Aktivnost/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Vaspitac")]

        public async Task<IActionResult> Create([Bind("id,nazivAktivnosti,tipAktivnosti,datumPocetka,datumZavrsetka,opis,idGrupe,idKorisnika,fotografija")] Aktivnost aktivnost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aktivnost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["idGrupe"] = new SelectList(_context.Grupa.ToList(), "id", "naziv", aktivnost.idGrupe);
            ViewBag.TipAktivnosti = new SelectList(Enum.GetValues(typeof(TipAktivnosti)));
            PostaviVaspitaceViewData(aktivnost.idKorisnika);
            return View(aktivnost);
        }

        // GET: Aktivnost/Edit/5
        [Authorize(Roles = "Administrator, Vaspitac")]

        public async Task<IActionResult> Edit(int? id)
        {
            var users = _userManager.Users.ToList();
            if (id == null)
            {
                return NotFound();
            }

            var aktivnost = await _context.Aktivnost.FindAsync(id);
            if (aktivnost == null)
            {
                return NotFound();
            }
            ViewData["idGrupe"] = new SelectList(_context.Grupa.ToList(), "id", "naziv");
            PostaviVaspitaceViewData(); 
            ViewBag.TipAktivnosti = new SelectList(Enum.GetValues(typeof(TipAktivnosti)));
            return View(aktivnost);
        }

        // POST: Aktivnost/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Vaspitac")]

        public async Task<IActionResult> Edit(int id, [Bind("id,nazivAktivnosti,tipAktivnosti,datumPocetka,datumZavrsetka,opis,idGrupe,idKorisnika,fotografija")] Aktivnost aktivnost)
        {
            if (id != aktivnost.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aktivnost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AktivnostExists(aktivnost.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["idGrupe"] = new SelectList(_context.Grupa.ToList(), "id", "naziv", aktivnost.idGrupe);
            ViewBag.TipAktivnosti = new SelectList(Enum.GetValues(typeof(TipAktivnosti)));
            PostaviVaspitaceViewData(aktivnost.idKorisnika);
            return View(aktivnost);
        }

        // GET: Aktivnost/Delete/5
        [Authorize(Roles = "Administrator, Vaspitac")]

        public async Task<IActionResult> Delete(int? id)
        {
            var users = _userManager.Users.ToList();
            if (id == null)
            {
                return NotFound();
            }

            var aktivnost = await _context.Aktivnost
                .Include(a => a.Grupa)
                .Include(a => a.Korisnik)
                .FirstOrDefaultAsync(m => m.id == id);
            if (aktivnost == null)
            {
                return NotFound();
            }

            ViewData["idGrupe"] = new SelectList(_context.Grupa.ToList(), "id", "naziv");
            PostaviVaspitaceViewData();
            ViewBag.TipAktivnosti = new SelectList(Enum.GetValues(typeof(TipAktivnosti)));

            return View(aktivnost);
        }

        // POST: Aktivnost/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Vaspitac")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aktivnost = await _context.Aktivnost.FindAsync(id);
            if (aktivnost != null)
            {
                _context.Aktivnost.Remove(aktivnost);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AktivnostExists(int id)
        {
            return _context.Aktivnost.Any(e => e.id == id);
        }
    }
}

PixelVrtic/PixelVrtic/Views/Aktivnost/Create.cshtml
@model PixelVrtic.Models.Aktivnost

@{
    ViewData["Title"] = "Dodaj aktivnost";
}

<style>
    body {
        background-color: #e0f7fa; /* baby blue background */
        font-family: 'Poppins', sans-serif;
    }

    .container {
        background: white;
        border-radius: 16px;
        padding: 40px;
        width: 60%;
        margin: 40px auto;
        box-shadow: 0px 4px 20px rgba(0,0,0,0.1);
    }

    h1 {
        font-size: 1.5rem;
        color: #2d2d5c;
        font-weight: 700;
        margin-bottom: 20px;
        text-align: center;
    }

    label {
        font-weight: 600;
        margin-top: 10px;
        display: block;
    }

    input, select, textarea {
        width: 100%;
        border: 1px solid #ccc;
        border-radius: 6px;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        font-family: 'Poppins', sans-serif;
    }

    .btn-submit {
        background-color: #d2f0fd;
        border: none;
        padding: 10px 30px;
        border-radius: 20px;
        color: #2d2d5c;
        font-weight: 600;
        cursor: pointer;
        display: block;
        margin: 0 auto;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }

        .btn-submit:hover {
            background-color: #a7e4fb;
        }

    .back-link {
        display: block;
        margin-top: 25px;
        text-align: center;
        color: #2d2d5c;
        text-decoration: none;
        font-weight: 600;
    }

    .text-danger {
        font-size: 0.9rem;
        margin-top: -10px;
        margin-bottom: 10px;
        display: block;
    }

    label {
        font-weight: 600;
        margin-top: 10px;
        display: block;
        text-transform: uppercase;
    }

</style>

<div class="container">
    <h1>Dodaj aktivnost</h1>

    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="nazivAktivnosti">Naziv aktivnosti</label>
            <input asp-for="nazivAktivnosti" />
            <span asp-validation-for="nazivAktivnosti" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="tipAktivnosti">Tip aktivnosti</label>
            <select asp-for="tipAktivnosti" asp-items="ViewBag.TipAktivnosti"></select>
            <span asp-validation-for="tipAktivnosti" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="datumPocetka">Datum početka</label>
            <input asp-for="datumPocetka" type="date" />
            <span asp-validation-for="datumPocetka" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="datumZavrsetka">Datum završetka</label>
            <input asp-for="datumZavrsetka" type="date" />
            <span asp-validation-for="datumZavrsetka" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="opis">Opis</label>
            <textarea asp-for="opis" rows="3"></textarea>
            <span asp-validation-for="opis" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="idGrupe">Grupa</label>
            <select asp-for="idGrupe" asp-items="ViewBag.idGrupe"></select>
            <span asp-validation-for="idGrupe" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="idKorisnika">Korisnik</label>
            <select asp-for="idKorisnika" asp-items="ViewBag.idKorisnika"></select>
            <span asp-validation-for="idKorisnika" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="fotografija">Fotografija</label>
            <input asp-for="fotografija" />
            <span asp-validation-for="fotografija" class="text-danger"></span>
        </div>

        <button type="submit" class="btn-submit">Dodaj</button>
    </form>

    <a asp-action="Index" class="back-link">⟵ Nazad na listu</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PixelVrtic/PixelVrtic/Views/Aktivnost/Delete.cshtml
@model PixelVrtic.Models.Aktivnost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aktivnost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nazivAktivnosti)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nazivAktivnosti)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipAktivnosti)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipAktivnosti)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.datumPocetka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.datumPocetka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.datumZavrsetka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.datumZavrsetka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grupa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grupa.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Korisnik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Korisnik.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fotografija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fotografija)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PixelVrtic/PixelVrtic/Views/Aktivnost/Details.cshtml
@model PixelVrtic.Models.Aktivnost

@{
    ViewData["Title"] = "Detalji aktivnosti";
}

<div class="page-container">
    <h1 class="details-title">Detalji aktivnosti</h1>

    <div class="details-card">
        <dl class="details-list">
            <dt>Naziv aktivnosti:</dt>
            <dd>@Model.nazivAktivnosti</dd>

            <dt>Tip aktivnosti:</dt>
            <dd>@Model.tipAktivnosti</dd>

            <dt>Datum početka:</dt>
            <dd>@Model.datumPocetka.ToString("dd.MM.yyyy HH:mm")</dd>

            <dt>Datum završetka:</dt>
            <dd>@(Model.datumZavrsetka.ToString("dd.MM.yyyy HH:mm") ?? "-")</dd>

            <dt>Opis:</dt>
            <dd>@(String.IsNullOrWhiteSpace(Model.opis) ? "-" : Model.opis)</dd>

            <dt>Grupa:</dt>
            <dd>@(Model.Grupa?.naziv ?? "Nije dodijeljeno")</dd>

            <dt>Korisnik:</dt>
            <dd>@(Model.Korisnik?.ime ?? "Nije dodijeljeno")</dd>
        </dl>
    </div>

    <div class="details-actions">
        @if (!User.IsInRole("Roditelj"))
        {
            <a asp-action="Edit" asp-route-id="@Model.id" class="btn btn-primary">Uredi</a>
        }
        
        <a asp-action="Index" class="btn btn-secondary">Nazad na listu</a>
    </div>
</div>

<style>
    /* Center page container vertically and horizontally */
    .page-container {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 24px;
        background-color: #f0f8ff; /* very light blue background for subtle contrast */
    }

    .details-title {
        color: #7ec8e3; /* baby blue */
        font-weight: 700;
        margin-bottom: 24px;
        font-size: 2rem;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        text-align: center;
    }

    .details-card {
        background-color: #ffffff; /* white card */
        border-radius: 16px;
        padding: 24px 32px;
        box-shadow: 0 4px 10px rgba(126, 200, 227, 0.3); /* baby blue shadow */
        max-width: 600px;
        width: 100%;
        margin-bottom: 32px;
    }

    .details-list {
        display: grid;
        grid-template-columns: max-content 1fr;
        gap: 12px 24px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #333;
        font-size: 1.1rem;
    }

        .details-list dt {
            font-weight: 700;
            color: #7ec8e3; /* baby blue */
            text-align: right;
            padding-right: 8px;
        }

        .details-list dd {
            margin: 0;
            padding-left: 8px;
            color: #555;
            word-wrap: break-word;
        }

    .details-actions {
        display: flex;
        gap: 16px;
        justify-content: center;
        width: 100%;
        max-width: 600px;
    }

    .btn {
        padding: 10px 24px;
        border-radius: 12px;
        font-weight: 600;
        font-size: 1rem;
        text-decoration: none;
        user-select: none;
        transition: background-color 0.2s ease;
        cursor: pointer;
        display: inline-block;
        border: none;
    }

    .btn-primary {
        background-color: #7ec8e3; /* baby blue */
        color: white;
    }

        .btn-primary:hover {
            background-color: #7ec8e3; /* darker baby blue */
        }

    .btn-secondary {
        background-color: #f5f5f5;
        color: #555;
        border: 1px solid #ddd;
    }

        .btn-secondary:hover {
            background-color: #e0e0e0;
        }

    html, body {
        margin: 0;
        padding: 0;
        background-color: #7ec8e3; /* baby blue, same as your background */
        height: 100%;
    }

    .sidebar {
        background-color: white; /* or whatever your sidebar background is */
        margin: 0;
        padding: 0;
        border: none;
    }

    .main-content {
        background-color: #7ec8e3; /* baby blue */
        margin: 0;
        padding: 0;
    }

    /* Also check if there is any border or box-shadow causing pink */

</style>

PixelVrtic/PixelVrtic/Views/Aktivnost/Index.cshtml
@model IEnumerable<PixelVrtic.Models.Aktivnost>
@{
    ViewData["Title"] = "Kalendar aktivnosti";

    int year = ViewBag.Year;
    int month = ViewBag.Month;
    var daysInMonth = DateTime.DaysInMonth(year, month);
    var firstDay = new DateTime(year, month, 1);
    var startDayOfWeek = (int)firstDay.DayOfWeek;
    if (startDayOfWeek == 0) startDayOfWeek = 7;

    var today = DateTime.Today;
    var monthName = System.Globalization.CultureInfo.GetCultureInfo("bs-BA").DateTimeFormat.GetMonthName(month);
    var currentYear = ViewBag.Year;
    var currentMonth = ViewBag.Month;
    bool AdminOrVaspitac = User.IsInRole("Administrator") || User.IsInRole("Vaspitac");

    var monthNames = System.Globalization.CultureInfo
        .GetCultureInfo("bs-BA")
        .DateTimeFormat
        .MonthNames
        .Take(12)
        .ToList();

    var years = Enumerable.Range(DateTime.Now.Year - 5, 11).ToList();
}

<form asp-action="Index" method="get" class="calendar-nav-dropdowns">
    <select name="month" onchange="this.form.submit()">
        @for (int i = 1; i <= 12; i++)
        {
            if (i == currentMonth)
            {
                <option value="@i" selected>@monthNames[i - 1]</option>
            }
            else
            {
                <option value="@i">@monthNames[i - 1]</option>
            }
        }
    </select>

    <select name="year" onchange="this.form.submit()">
        @foreach (var y in years)
        {
            if (y == currentYear)
            {
                <option value="@y" selected>@y</option>
            }
            else
            {
                <option value="@y">@y</option>
            }
        }
    </select>
</form>


<div class="calendar-header">
    <h2>@monthName @year</h2>
    <div class="calendar-nav">
        <a asp-action="Index" asp-route-month="@(month == 1 ? 12 : month - 1)" asp-route-year="@(month == 1 ? year - 1 : year)">«</a>
        <a asp-action="Index" asp-route-month="@(month == 12 ? 1 : month + 1)" asp-route-year="@(month == 12 ? year + 1 : year)">»</a>
    </div>
</div>

<div class="calendar-grid">
    @foreach (var dayName in new[] { "Pon", "Uto", "Sri", "Čet", "Pet", "Sub", "Ned" })
    {
        <div class="calendar-day-name">@dayName</div>
    }

    @for (int i = 1; i < startDayOfWeek; i++)
    {
        <div class="calendar-day empty"></div>
    }
    @for (int day = 1; day <= daysInMonth; day++)
    {
        var currentDate = new DateTime(year, month, day);
        var dayActivities = Model.Where(a => a.datumPocetka.Date == currentDate).ToList();
        var isToday = currentDate.Date == today;

        <div class="calendar-day @(isToday ? "today" : "")" style="cursor:pointer;"
             onclick="location.href='@Url.Action(AdminOrVaspitac ? "Create" : "Index", "Aktivnost")?datumPocetka=@currentDate.ToString("yyyy-MM-dd")'">

            <div class="date-number">@day</div>

            @if (dayActivities.Any())
            {
                @foreach (var activity in dayActivities)
                {
                    <div class="activity-tooltip">
                        @if (ViewBag.IsAuthorizedUser == true)
                        {
                            <div class="activity-dot"
                                 onclick="event.stopPropagation(); location.href='@Url.Action(AdminOrVaspitac ? "Edit" : "Details", "Aktivnost", new { id = activity.id })'">
                            </div>
                        }
                        else
                        {
                            <div class="activity-dot"></div>
                        }

                        <div class="activity-popup">
                            <div class="activity-card">
                                <strong>@activity.nazivAktivnosti</strong><br />
                                Grupa: @activity.Grupa?.naziv<br />
                                Korisnik: @activity.Korisnik?.ime
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    }


</div>
<style>
    .body{
        background-color: #fde9f0;
    }

    .calendar-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
    }

    .calendar-nav a {
        text-decoration: none;
        font-weight: bold;
        font-size: 18px;
        margin: 0 10px;
        color: #333;
    }

    .calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 10px;
        padding: 10px;
    }

    .calendar-day-name {
        text-align: center;
        font-weight: bold;
        padding: 8px;
        background: #f0f0f0;
        border-radius: 8px;
    }

    .calendar-day {
        background-color: white;
        border: 1px solid #ddd;
        border-radius: 12px;
        padding: 8px;
        min-height: 90px;
        position: relative;
        transition: all 0.2s ease-in-out;
    }

        .calendar-day.today {   
            border: 2px solid #ff7043;
        }

        .calendar-day.empty {
            background-color: #f9f9f9;
            border: none;
        }

    .date-number {
        font-weight: bold;
        font-size: 14px;
    }

    .activity-dot {
        width: 10px;
        height: 10px;
        background-color: #FF7043;
        border-radius: 50%;
        margin-top: 6px;
    }

    .calendar-nav-dropdowns {
        display: flex;
        gap: 12px;
        margin: 20px;
        justify-content: center;
    }

        .calendar-nav-dropdowns select {
            padding: 8px 14px;
            font-size: 16px;
            border: 1px solid #dce2f0;
            border-radius: 12px;
            background-color: #f5faff;
            color: #333;
            cursor: pointer;
            outline: none;
            transition: 0.2s ease-in-out;
        }

            .calendar-nav-dropdowns select:hover {
                background-color: #eaf5ff;
                border-color: #a8cfff;
            }

    .calendar-day {
        position: relative;
        padding: 8px;
        border-radius: 12px;
        background-color: white;
        border: 1px solid #ddd;
        min-height: 90px;
    }

        .calendar-day.today {
            border: 2px solid #ff7043;
        }

    .activity-tooltip {
        position: relative;
        display: inline-block;
    }

    .activity-dot {
        width: 12px;
        height: 12px;
        background-color: #FF7043;
        border-radius: 50%;
        margin-top: 6px;
        cursor: pointer;
    }

    .activity-popup {
        display: none;
        position: absolute;
        z-index: 10;
        top: 20px;
        left: 0;
        background-color: #fff;
        color: #333;
        border: 1px solid #ccc;
        border-radius: 12px;
        padding: 10px;
        width: 220px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

        .activity-tooltip:hover .activity-popup,
        .activity-popup:hover {
            display: block;
        }


    .activity-card {
        margin-bottom: 8px;
        font-size: 14px;
        line-height: 1.4;
    }

        .activity-card:last-child {
            margin-bottom: 0;
        }

    .activity-card {
        cursor: pointer;
    }

    .activity-dot {
        cursor: pointer;
    }

    .calendar-day:hover {
        background-color: #fff2e6; /* subtle highlight on hover */
        border-color: #ff7043;
        cursor: pointer;
    }
</style>